name: Go Build

on:
  workflow_call:

jobs:

  go-build:
    name: Go Build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22

      - name: Get source
        uses: actions/checkout@v4

      - name: Get deps
        run: make deps

      - name: Build bot
        run: make build-go
